---
title: "Cassandra & Michael Wedding Details"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Saturday, March 24, 2018
5:00 PM
Attire: Semiformal
 
### Ceremony and Reception
The Tiger Hotel
23 S 8th St, Columbia, MO 65201
(573) 875-8888
 
Adult Reception


### Hotel Accommodations

The Tiger Hotel [Wedding Venue]
23 S 8th St, Columbia, MO 65201
Phone: (573) 875-8888
Website: http://www.thetigerhotel.com/

Rooms at a discounted rate with our hotel block can be accessed by calling the above phone number and mentioning "Bird/Kearney Wedding"

Double-- $182 a night
King-- $162 a night

Must book by January 24, 2018 to receive discounted rate

The Broadway Columbia—DoubleTree by Hilton Hotel
1111 E Broadway, Columbia, MO 65201
Phone: (573) 875-7000
Website: http://doubletree3.hilton.com/en/hotels/missouri/the-broadway-columbia-a-doubletree-by-hilton-hotel-COUTBDT/index.html

The DoubleTree Hotel is a scenic 6-minute walk through historic downtown Columbia from the wedding venue. Rooms at a discounted rate with our hotel block can be accessed through their website or by calling the above phone number and mentioning "Bird/Kearney Wedding"

Double-- ??
King-- ??

Must book by ??????

### Airline Travel Information

St. Louis Lambert International Airport (STL)
10701 Lambert International Blvd, St. Louis, MO 63145
Website: https://www.flystl.com/

The St. Louis Airport is approximately 111 miles (or 1 hour and 42 minutes) from the wedding venue. While there is a shuttle service to and from Columbia for a reasonable fare, we recommend renting a car for your convenience. 

Rental Cars from Lambert International Airport
https://www.flystl.com/parking-and-transport/rental-cars

Kansas City International Airport (MCI)
Kansas City, MO 64153
Website: http://www.flykci.com/

The Kansas City airport is approximately 146 miles (or 2 hours and 12 minutes) from the wedding venue. While there is shuttle service to and from Columbia for a reasonable fare, we recommend renting a car for your convenience. 

Rental Cars from Kansas City International Airport
http://www.flykci.com/getting-to-from/ground-transportation/rental-car-services/

Columbia Regional Airport (COU)
11300 S Airport Dr, Columbia, MO 65201
Website: https://www.flycou.com/

The Columbia Airport is 13 miles (or 19 minutes) from the wedding venue. A little more expensive, but much closer to the wedding venue. Columbia Regional Airport is served by American Airlines and United Airlines providing reliable and convenient direct, non-stop flights from Columbia to Dallas/Fort Worth, Chicago O'Hare and Denver International Airports! 

Rental Cars/Taxies from Columbia Regional Airport
https://www.flycou.com/?page_id=98
https://www.flycou.com/?page_id=96

Airport Shuttle Services

MOX Airport Shuttle (St. Louis and Kansas City)
Website: http://moexpress.com/moxolrs/Pricing.aspx 
Fare: Approximately $108 round trip

EZGO Bus (only to St. Louis)
Website: http://www.ezgobusmo.com/book-your-ride/ 
Fare: Approximately $80 round trip

### Restaurants and Good Eats

Glenn’s Café
29 S 8th St, Columbia, MO 65201
Website: http://www.glennscafe.com/

Located in the Tiger Hotel, “familiar Cajun-Creole & American dishes are the draw at this local eatery with a relaxed atmosphere.” We love their Jambalaya!

Flat Branch Pub & Brewing
115 S 5th St, Columbia, MO 65201
Website: https://www.flatbranch.com/

4-minute walk, this very popular destination is a “warehouse setting for house-brewed beer, a big selection of whiskey & upscale American pub fare.” REALLY good beer ☺

Addison’s: An American Grill
709 Cherry St, Columbia, MO 65201
http://www.addisonsgrill.com/

A 1-minute walk from the tiger hotel, Addison’s is a “convivial eatery, decorated in colorful paintings, boasts an eclectic menu & a happy hour.”

Shakespeare’s Pizza
225 S 9th St, Columbia, MO 65201
Website: https://shakespeares.com/

A 4-minute walk from the Tiger Hotel, “this old-school popular pizza joint serves up traditional hand-tossed pies in a laid-back homey setting.” In our opinion, the pizza is best if you eat it there!

Sparky’s Homemade Ice Cream
S 9th St, Columbia, MO 65201
Website: https://www.facebook.com/sparkyshomemade/

If you are looking to stroll for dessert, Sparky’s is a 2-minute walk from the Tiger Hotel to a “Cozy shop serving housemade ice cream in a casual space with eclectic art on the walls.” Mike highly recommends the cinnamon ice cream, Casi prefers a classic chocolate!

Kaldi’s Coffee
29 S 9th St #1, Columbia, MO 65201
https://kaldiscoffee.com/

If you want to get a little local coffee, we love Kaldi’s. It’s a 2-minute walk from the Tiger Hotel and they are a “chill coffeehouse specializing in coffee & espresso drinks made from carefully sourced beans.” Highly recommend the vanilla latte!


